on:
  pull_request:
    types: [ opened, reopened, ready_for_review ]
    paths-ignore:
      - 'assets/**'

jobs:

  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' && !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          CONFIG.MODEL: "gemini/gemini-2.5-pro-exp-03-25"
          CONFIG.FALLBACK_MODELS: '["gemini/gemini-1.5-flash"]'
    
